### PR TITLE
Add Lauren Tan

### PR DESCRIPTION
**Pull request by mike-north**

### CODE REVIEW

**Comment by iheanyi** [comment]
Just to make sure she's okay with this: @poteto, are you comfortable being added to this list? :)

**Comment by poteto** [comment]
@iheanyi yes, thanks for asking :) and thanks for adding me @mike-north 🍭

**Comment by jalcine** [comment]
Thanks everyone! 👍

**Comment by mmccullar** [comment]
Thank you for this! Wasn't able to attend so this is like Christmas came early =D

**Pull request merged**
