### PR TITLE
Add Taylor Barnett and intro text

### PR DESCRIPTION
**Pull request by tbarn**
Super excited about this! 💪

### CODE REVIEW

**Comment by mrmrs** [comment]
@tbarn I manually added your info here: c6a66a35eaa8ec49ecdf11f91ab16d2f9e25e740

Want to double check with @iheanyi on the copy change. It looks great to me. Thanks for taking the time on that. How does this look to you @iheanyi ? If you give the thumbs up I'll add it in.

**Comment by iheanyi** [comment]
@mrmrs Oh crap, I just got alerted about this. The Copy Change is great, Taylor DMed me about this before and I gave her the sign off. Let's ship it! :D

**Comment by tbarn** [comment]
I can open a new PR with just this wording if it makes merging easier. Just let me know. :)

**Comment by iheanyi** [comment]
@tbarn Yes please. :)

**Pull request closed without merging**
